apiVersion: v1
kind: Pod
metadata:
  name: dnscheck
  namespace: default
spec:
  containers:
  - name: dnscheck
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
